{
 "title": "Server Overview - (CollectD/Prometheus) [release 2.0.3]",
 "description": "CollectD & Prometheus Server Metrics (CPU, Memory, IO, Disks)",
 "tags": [
  "collectd",
  "infrastructure"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "query": {
     "query": "label_values(collectd_uptime,exported_instance)"
    }
   },
   {
    "name": "timeperiod",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Quick view for: $server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Total uptime for all selected servers",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(collectd_uptime{exported_instance=~\"$server\"}[1m]))",
     "legendFormat": "uptime"
    }
   ]
  },
  {
   "title": "Logged users",
   "type": "stat",
   "description": "Users logged in for all selected servers for selected time range",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(collectd_users{exported_instance=~\"$server\"})",
     "legendFormat": "users"
    }
   ]
  },
  {
   "title": "Load Avg (5m)",
   "type": "bargauge",
   "description": "Load average for all selected servers for selected time range",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(collectd_load_midterm{exported_instance=~\"$server\"}[$__rate_interval]))",
     "legendFormat": "midterm"
    }
   ]
  },
  {
   "title": "Zombies",
   "type": "stat",
   "description": "Zombies for all selected servers for selected time range",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(collectd_processes_ps_state{processes=\"zombies\",exported_instance=~\"$server\"}[$__rate_interval]))",
     "legendFormat": "zombies"
    }
   ]
  },
  {
   "title": "Procs run",
   "type": "stat",
   "description": "Running procs for all selected servers for selected time range",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(collectd_processes_ps_state{processes=\"running\", exported_instance=~\"$server\"}[$__rate_interval]))",
     "legendFormat": "running"
    }
   ]
  },
  {
   "title": "Procs blocked",
   "type": "stat",
   "description": "Blocked procs for all selected servers for selected time range",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(collectd_processes_ps_state{processes=\"blocked\", exported_instance=~\"$server\"}[$__rate_interval]))",
     "legendFormat": "blocked"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "CPU usage average for all selected servers for selected time range",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(collectd_cpu_percent{exported_instance=~\"$server\", type=~\"user|system\"}[$__rate_interval])) / count(last_over_time(collectd_cpu_percent{exported_instance=~\"$server\", type=~\"idle\"}[$__rate_interval]))",
     "legendFormat": "CPU usage for all selected servers for selected time range"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "description": "RAM usage for all selected servers for selected time range (not average!)",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(collectd_memory{exported_instance=~\"$server\", memory=\"used\"}[$__rate_interval])) / sum(last_over_time(collectd_memory {exported_instance=~\"$server\", memory=~\".*\"}[$__rate_interval])) * 100",
     "legendFormat": "ram usage"
    }
   ]
  },
  {
   "title": "SWAP Usage",
   "type": "gauge",
   "description": "SWAP usage for all selected servers for selected time range (not average!)",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(collectd_swap{exported_instance=~\"$server\", swap=~\"used|cache\"}[$__rate_interval])) / sum(last_over_time(collectd_swap{exported_instance=~\"$server\", swap=~\".*\"}[$__rate_interval])) * 100",
     "legendFormat": "swap"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "description": "Disk usage (only root fs) for all selected servers for selected time range (not average!)",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(collectd_df_df_complex{exported_instance=~\"$server\", df=\"root\", type=\"used\"}[$__rate_interval])) / sum(last_over_time(collectd_df_df_complex{exported_instance=~\"$server\", df=\"root\", type=~\".*\"}[$__rate_interval])) * 100",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "Disk Inodes (root)",
   "type": "gauge",
   "description": "Disk Inodes usage (only root fs) for all selected servers for selected time range (not average!)",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(collectd_df_df_inodes{exported_instance=~\"$server\", df=\"root\", type=\"used\"}[$__rate_interval])) / sum(last_over_time(collectd_df_df_inodes{exported_instance=~\"$server\", df=\"root\", type=~\".*\"}[$__rate_interval])) * 100",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "piechart",
   "description": "Disk usage (only root fs) for all selected servers for selected time range (not average!)",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(type) (collectd_df_percent_bytes{exported_instance=~\"$server\", df=\"root\"}) / count by(type) (collectd_df_percent_bytes{exported_instance=~\"$server\", df=\"root\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "CPU / Processes / Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(sum by(cpu, exported_instance) (collectd_cpu_percent{exported_instance=~\"$server\", type!=\"idle\"}), \"cpu\", \"cpu-$1\", \"cpu\", \"(.*)\")",
     "legendFormat": "{{exported_instance}}.{{cpu}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(exported_instance) (collectd_load_longterm{exported_instance=~\"$server\"})",
     "legendFormat": "{{exported_instance}}.long"
    },
    {
     "expr": "sum by(exported_instance) (collectd_load_midterm{exported_instance=~\"$server\"})",
     "legendFormat": "{{exported_instance}}.mid"
    },
    {
     "expr": "sum by(exported_instance) (collectd_load_shortterm{exported_instance=~\"$server\"})",
     "legendFormat": "{{exported_instance}}.short"
    }
   ]
  },
  {
   "title": "Process Fork/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(collectd_processes_fork_rate_total{exported_instance=~\"$server\"}[1m])",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "collectd_processes_ps_state{exported_instance=~\"$server\", processes!=\"sleeping\"}",
     "legendFormat": "{{exported_instance}}.{{processes}}"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "sum by(exported_instance, memory) (collectd_memory{exported_instance=~\"$server\"})",
     "legendFormat": "{{exported_instance}}.{{memory}}"
    },
    {
     "expr": "sum  (collectd_memory{exported_instance=~\"$server\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(exported_instance) (collectd_swap{exported_instance=~\"$server\", swap=\"used\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Disk Usage %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(df, exported_instance) (collectd_df_percent_bytes{exported_instance=~\"$server\", type=\"used\"})",
     "legendFormat": "{{exported_instance}}.{{df}}"
    }
   ]
  },
  {
   "title": "Disk Inodes %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(df, exported_instance) (collectd_df_percent_inodes{exported_instance=~\"$server\", type=\"used\"})",
     "legendFormat": "{{exported_instance}}.{{df}}"
    }
   ]
  },
  {
   "title": "Disk - Time per operation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(exported_instance, disk) (rate(collectd_disk_disk_io_time_weighted_io_time_total{exported_instance=~\"$server\"}[$__rate_interval]))",
     "legendFormat": "{{exported_instance}}.{{disk}}.weighted-io"
    },
    {
     "expr": "sum by(disk, exported_instance) (rate(collectd_disk_disk_io_time_io_time_total{exported_instance=~\"$server\"}[$__rate_interval]) * 0.01)",
     "legendFormat": "{{exported_instance}}.{{disk}}.io-time"
    }
   ]
  },
  {
   "title": "Disk - Time spent doing I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(exported_instance, disk) (rate(collectd_disk_disk_time_read_total{exported_instance=~\"$server\"}[$__rate_interval]))",
     "legendFormat": "{{exported_instance}}.{{disk}}.read"
    },
    {
     "expr": "sum by(exported_instance, disk) (rate(collectd_disk_disk_time_write_total{exported_instance=~\"$server\"}[$__rate_interval]))",
     "legendFormat": "{{exported_instance}}.{{disk}}.write"
    }
   ]
  },
  {
   "title": "Disk - Merged ops",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(exported_instance, disk) (rate(collectd_disk_disk_merged_read_total{exported_instance=~\"$server\"}[$__rate_interval]))",
     "legendFormat": "{{exported_instance}}.{{disk}}.read"
    },
    {
     "expr": "sum by(exported_instance, disk) (rate(collectd_disk_disk_merged_write_total{exported_instance=~\"$server\"}[$__rate_interval]))",
     "legendFormat": "{{exported_instance}}.{{disk}}.write"
    }
   ]
  },
  {
   "title": "Disk - Operations per second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(exported_instance, disk) (rate(collectd_disk_disk_ops_read_total{exported_instance=~\"$server\"}[$__rate_interval]))",
     "legendFormat": "{{exported_instance}}.{{disk}}.read"
    },
    {
     "expr": "sum by(exported_instance, disk) (rate(collectd_disk_disk_ops_write_total{exported_instance=~\"$server\"}[$__rate_interval]))",
     "legendFormat": "{{exported_instance}}.{{disk}}.write"
    }
   ]
  },
  {
   "title": "Disk - Pending I/O requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(exported_instance, disk) (collectd_disk_pending_operations{exported_instance=~\"$server\"})",
     "legendFormat": "{{exported_instance}}.{{disk}}"
    }
   ]
  },
  {
   "title": "Disk - Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(exported_instance, disk) (rate(collectd_disk_disk_octets_read_total{exported_instance=~\"$server\"}[$__rate_interval]))",
     "legendFormat": "{{exported_instance}}.{{disk}}.read"
    },
    {
     "expr": "sum by(exported_instance, disk) (rate(collectd_disk_disk_octets_write_total{exported_instance=~\"$server\"}[$__rate_interval]))",
     "legendFormat": "{{exported_instance}}.{{disk}}.write"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Network Traffic/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by(exported_instance, interface) (rate(collectd_interface_if_octets_rx_total{exported_instance=~\"$server\"}[$__rate_interval]))",
     "legendFormat": "{{exported_instance}}.{{interface}}.rx"
    },
    {
     "expr": "sum by(exported_instance, interface) (rate(collectd_interface_if_octets_tx_total{exported_instance=~\"$server\"}[$__rate_interval]))",
     "legendFormat": "{{exported_instance}}.{{interface}}.tx"
    }
   ]
  },
  {
   "title": "Network Packets/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(exported_instance, interface) (rate(collectd_interface_if_packets_rx_total{exported_instance=~\"$server\"}[$__rate_interval]))",
     "legendFormat": "{{exported_instance}}.{{interface}}.rx"
    },
    {
     "expr": "sum by(exported_instance, interface) (rate(collectd_interface_if_packets_tx_total{exported_instance=~\"$server\"}[$__rate_interval]))",
     "legendFormat": "{{exported_instance}}.{{interface}}.tx"
    }
   ]
  },
  {
   "title": "Network Errors/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(exported_instance, interface) (rate(collectd_interface_if_errors_tx_total{exported_instance=~\"$server\"}[$__rate_interval]))\n\n",
     "legendFormat": "{{exported_instance}}.{{interface}}.tx"
    },
    {
     "expr": "sum by(exported_instance, interface) (rate(collectd_interface_if_errors_rx_total{exported_instance=~\"$server\"}[$__rate_interval]))",
     "legendFormat": "{{exported_instance}}.{{interface}}.rx"
    }
   ]
  },
  {
   "title": "Dropped Packets/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(exported_instance, interface) (rate(collectd_interface_if_dropped_tx_total{exported_instance=~\"$server\"}[$__rate_interval]))\n\n",
     "legendFormat": "{{exported_instance}}.{{interface}}.tx"
    },
    {
     "expr": "sum by(exported_instance, interface) (rate(collectd_interface_if_dropped_rx_total{exported_instance=~\"$server\"}[$__rate_interval]))",
     "legendFormat": "{{exported_instance}}.{{interface}}.rx"
    }
   ]
  },
  { "title": "TCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "TCP all",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "sum by(exported_instance, type) (collectd_tcpconns_tcp_connections{exported_instance=~\"$server\", tcpconns=\"all\"})",
     "legendFormat": "{{exported_instance}}.{{type}}"
    }
   ]
  },
  {
   "title": "TCP 22",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "sum by(exported_instance, type) (collectd_tcpconns_tcp_connections{exported_instance=~\"$server\", tcpconns=\"22-local\"})",
     "legendFormat": "{{exported_instance}}.{{type}}"
    }
   ]
  },
  {
   "title": "TCP 443",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "sum by(exported_instance, type) (collectd_tcpconns_tcp_connections{exported_instance=~\"$server\", tcpconns=\"443-local\"})",
     "legendFormat": "{{exported_instance}}.{{type}}"
    }
   ]
  },
  {
   "title": "TCP 6443",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "sum by(exported_instance, type) (collectd_tcpconns_tcp_connections{exported_instance=~\"$server\", tcpconns=\"6443-local\"})",
     "legendFormat": "{{exported_instance}}.{{type}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Users logged in",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max_over_time(collectd_users{exported_instance=~\"$server\"}[1m])",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Temperature / Fan",
   "type": "timeseries",
   "description": "Shows temperature in Celsius and fan speed in r/min",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "collectd_sensors_temperature{exported_instance=~\"$server\", type=~\"temp1\"}",
     "legendFormat": "{{exported_instance}}.{{sensors}}"
    },
    {
     "expr": "collectd_sensors_fanspeed{exported_instance=~\"$server\"}",
     "legendFormat": "{{exported_instance}}.fan"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "collectd_sensors_voltage{exported_instance=~\"$server\", type=\"in0\"}",
     "legendFormat": "{{exported_instance}}.{{sensors}}"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "collectd_sensors_current{exported_instance=~\"$server\", type=\"curr1\"}",
     "legendFormat": "{{exported_instance}}.{{sensors}}"
    }
   ]
  }
 ]
}